language: python
python: 2.7
dist: xenial
sudo: true

# command to install dependencies
install:
    - pip check

# command to run tests
script:
    - pytest

notifications:
  email:
    on_success: change
    on_failure: change
